export const quotes: string[] = [
  "Good things take time",
  "Almost there… great things loading",
  "Loading your experience, please wait",
  "Patience is the key to something amazing",
  "Preparing something awesome for you",
  "Hang tight! We’re getting things ready",
  "Every moment counts—loading in progress",
  "Your content is on its way",
  "Getting things ready for you",
  "Just a moment — we're on it",
  "Loading your experience",
  "Almost there",
  "Good things take a moment",
  "Thanks for your patience",
  "Worth the wait",
  "Something good is coming",
  "Preparing something awesome",
  "Your journey continues",
  "Hang tight",
  "We’re setting things up",
  "Making things smooth for you",
];
